/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BooksImport } from './routes/books'
import { Route as IndexImport } from './routes/index'
import { Route as WizformsBookIdImport } from './routes/wizforms.$bookId'
import { Route as MapBookIdIndexImport } from './routes/map.$bookId/index'
import { Route as WizformsBookIdFocusedIdImport } from './routes/wizforms.$bookId/focused.$id'
import { Route as MapBookIdSectionIdImport } from './routes/map.$bookId/section.$id'

// Create/Update Routes

const BooksRoute = BooksImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WizformsBookIdRoute = WizformsBookIdImport.update({
  id: '/wizforms/$bookId',
  path: '/wizforms/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const MapBookIdIndexRoute = MapBookIdIndexImport.update({
  id: '/map/$bookId/',
  path: '/map/$bookId/',
  getParentRoute: () => rootRoute,
} as any)

const WizformsBookIdFocusedIdRoute = WizformsBookIdFocusedIdImport.update({
  id: '/focused/$id',
  path: '/focused/$id',
  getParentRoute: () => WizformsBookIdRoute,
} as any)

const MapBookIdSectionIdRoute = MapBookIdSectionIdImport.update({
  id: '/map/$bookId/section/$id',
  path: '/map/$bookId/section/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksImport
      parentRoute: typeof rootRoute
    }
    '/wizforms/$bookId': {
      id: '/wizforms/$bookId'
      path: '/wizforms/$bookId'
      fullPath: '/wizforms/$bookId'
      preLoaderRoute: typeof WizformsBookIdImport
      parentRoute: typeof rootRoute
    }
    '/map/$bookId/': {
      id: '/map/$bookId/'
      path: '/map/$bookId'
      fullPath: '/map/$bookId'
      preLoaderRoute: typeof MapBookIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/map/$bookId/section/$id': {
      id: '/map/$bookId/section/$id'
      path: '/map/$bookId/section/$id'
      fullPath: '/map/$bookId/section/$id'
      preLoaderRoute: typeof MapBookIdSectionIdImport
      parentRoute: typeof rootRoute
    }
    '/wizforms/$bookId/focused/$id': {
      id: '/wizforms/$bookId/focused/$id'
      path: '/focused/$id'
      fullPath: '/wizforms/$bookId/focused/$id'
      preLoaderRoute: typeof WizformsBookIdFocusedIdImport
      parentRoute: typeof WizformsBookIdImport
    }
  }
}

// Create and export the route tree

interface WizformsBookIdRouteChildren {
  WizformsBookIdFocusedIdRoute: typeof WizformsBookIdFocusedIdRoute
}

const WizformsBookIdRouteChildren: WizformsBookIdRouteChildren = {
  WizformsBookIdFocusedIdRoute: WizformsBookIdFocusedIdRoute,
}

const WizformsBookIdRouteWithChildren = WizformsBookIdRoute._addFileChildren(
  WizformsBookIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRoute
  '/wizforms/$bookId/focused/$id': typeof WizformsBookIdFocusedIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRoute
  '/wizforms/$bookId/focused/$id': typeof WizformsBookIdFocusedIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId/': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRoute
  '/wizforms/$bookId/focused/$id': typeof WizformsBookIdFocusedIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/wizforms/$bookId'
    | '/map/$bookId'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/focused/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/wizforms/$bookId'
    | '/map/$bookId'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/focused/$id'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/wizforms/$bookId'
    | '/map/$bookId/'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/focused/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  WizformsBookIdRoute: typeof WizformsBookIdRouteWithChildren
  MapBookIdIndexRoute: typeof MapBookIdIndexRoute
  MapBookIdSectionIdRoute: typeof MapBookIdSectionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  WizformsBookIdRoute: WizformsBookIdRouteWithChildren,
  MapBookIdIndexRoute: MapBookIdIndexRoute,
  MapBookIdSectionIdRoute: MapBookIdSectionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books",
        "/wizforms/$bookId",
        "/map/$bookId/",
        "/map/$bookId/section/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/books": {
      "filePath": "books.tsx"
    },
    "/wizforms/$bookId": {
      "filePath": "wizforms.$bookId.tsx",
      "children": [
        "/wizforms/$bookId/focused/$id"
      ]
    },
    "/map/$bookId/": {
      "filePath": "map.$bookId/index.tsx"
    },
    "/map/$bookId/section/$id": {
      "filePath": "map.$bookId/section.$id.tsx"
    },
    "/wizforms/$bookId/focused/$id": {
      "filePath": "wizforms.$bookId/focused.$id.tsx",
      "parent": "/wizforms/$bookId"
    }
  }
}
ROUTE_MANIFEST_END */
