/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WizformsBookIdImport } from './routes/wizforms/$bookId'
import { Route as MapBookIdIndexImport } from './routes/map.$bookId/index'
import { Route as WizformsBookIdFocusedIdModalImport } from './routes/wizforms/$bookId.$focusedId.modal'
import { Route as MapBookIdSectionIdImport } from './routes/map.$bookId/section.$id'
import { Route as MapBookIdSectionIdFocusedIdModalImport } from './routes/map.$bookId/section.$id.$focusedId.modal'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WizformsBookIdRoute = WizformsBookIdImport.update({
  id: '/wizforms/$bookId',
  path: '/wizforms/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const MapBookIdIndexRoute = MapBookIdIndexImport.update({
  id: '/map/$bookId/',
  path: '/map/$bookId/',
  getParentRoute: () => rootRoute,
} as any)

const WizformsBookIdFocusedIdModalRoute =
  WizformsBookIdFocusedIdModalImport.update({
    id: '/$focusedId/modal',
    path: '/$focusedId/modal',
    getParentRoute: () => WizformsBookIdRoute,
  } as any)

const MapBookIdSectionIdRoute = MapBookIdSectionIdImport.update({
  id: '/map/$bookId/section/$id',
  path: '/map/$bookId/section/$id',
  getParentRoute: () => rootRoute,
} as any)

const MapBookIdSectionIdFocusedIdModalRoute =
  MapBookIdSectionIdFocusedIdModalImport.update({
    id: '/$focusedId/modal',
    path: '/$focusedId/modal',
    getParentRoute: () => MapBookIdSectionIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/wizforms/$bookId': {
      id: '/wizforms/$bookId'
      path: '/wizforms/$bookId'
      fullPath: '/wizforms/$bookId'
      preLoaderRoute: typeof WizformsBookIdImport
      parentRoute: typeof rootRoute
    }
    '/map/$bookId/': {
      id: '/map/$bookId/'
      path: '/map/$bookId'
      fullPath: '/map/$bookId'
      preLoaderRoute: typeof MapBookIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/map/$bookId/section/$id': {
      id: '/map/$bookId/section/$id'
      path: '/map/$bookId/section/$id'
      fullPath: '/map/$bookId/section/$id'
      preLoaderRoute: typeof MapBookIdSectionIdImport
      parentRoute: typeof rootRoute
    }
    '/wizforms/$bookId/$focusedId/modal': {
      id: '/wizforms/$bookId/$focusedId/modal'
      path: '/$focusedId/modal'
      fullPath: '/wizforms/$bookId/$focusedId/modal'
      preLoaderRoute: typeof WizformsBookIdFocusedIdModalImport
      parentRoute: typeof WizformsBookIdImport
    }
    '/map/$bookId/section/$id/$focusedId/modal': {
      id: '/map/$bookId/section/$id/$focusedId/modal'
      path: '/$focusedId/modal'
      fullPath: '/map/$bookId/section/$id/$focusedId/modal'
      preLoaderRoute: typeof MapBookIdSectionIdFocusedIdModalImport
      parentRoute: typeof MapBookIdSectionIdImport
    }
  }
}

// Create and export the route tree

interface WizformsBookIdRouteChildren {
  WizformsBookIdFocusedIdModalRoute: typeof WizformsBookIdFocusedIdModalRoute
}

const WizformsBookIdRouteChildren: WizformsBookIdRouteChildren = {
  WizformsBookIdFocusedIdModalRoute: WizformsBookIdFocusedIdModalRoute,
}

const WizformsBookIdRouteWithChildren = WizformsBookIdRoute._addFileChildren(
  WizformsBookIdRouteChildren,
)

interface MapBookIdSectionIdRouteChildren {
  MapBookIdSectionIdFocusedIdModalRoute: typeof MapBookIdSectionIdFocusedIdModalRoute
}

const MapBookIdSectionIdRouteChildren: MapBookIdSectionIdRouteChildren = {
  MapBookIdSectionIdFocusedIdModalRoute: MapBookIdSectionIdFocusedIdModalRoute,
}

const MapBookIdSectionIdRouteWithChildren =
  MapBookIdSectionIdRoute._addFileChildren(MapBookIdSectionIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRouteWithChildren
  '/wizforms/$bookId/$focusedId/modal': typeof WizformsBookIdFocusedIdModalRoute
  '/map/$bookId/section/$id/$focusedId/modal': typeof MapBookIdSectionIdFocusedIdModalRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRouteWithChildren
  '/wizforms/$bookId/$focusedId/modal': typeof WizformsBookIdFocusedIdModalRoute
  '/map/$bookId/section/$id/$focusedId/modal': typeof MapBookIdSectionIdFocusedIdModalRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/wizforms/$bookId': typeof WizformsBookIdRouteWithChildren
  '/map/$bookId/': typeof MapBookIdIndexRoute
  '/map/$bookId/section/$id': typeof MapBookIdSectionIdRouteWithChildren
  '/wizforms/$bookId/$focusedId/modal': typeof WizformsBookIdFocusedIdModalRoute
  '/map/$bookId/section/$id/$focusedId/modal': typeof MapBookIdSectionIdFocusedIdModalRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wizforms/$bookId'
    | '/map/$bookId'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/$focusedId/modal'
    | '/map/$bookId/section/$id/$focusedId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wizforms/$bookId'
    | '/map/$bookId'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/$focusedId/modal'
    | '/map/$bookId/section/$id/$focusedId/modal'
  id:
    | '__root__'
    | '/'
    | '/wizforms/$bookId'
    | '/map/$bookId/'
    | '/map/$bookId/section/$id'
    | '/wizforms/$bookId/$focusedId/modal'
    | '/map/$bookId/section/$id/$focusedId/modal'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WizformsBookIdRoute: typeof WizformsBookIdRouteWithChildren
  MapBookIdIndexRoute: typeof MapBookIdIndexRoute
  MapBookIdSectionIdRoute: typeof MapBookIdSectionIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WizformsBookIdRoute: WizformsBookIdRouteWithChildren,
  MapBookIdIndexRoute: MapBookIdIndexRoute,
  MapBookIdSectionIdRoute: MapBookIdSectionIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wizforms/$bookId",
        "/map/$bookId/",
        "/map/$bookId/section/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wizforms/$bookId": {
      "filePath": "wizforms/$bookId.tsx",
      "children": [
        "/wizforms/$bookId/$focusedId/modal"
      ]
    },
    "/map/$bookId/": {
      "filePath": "map.$bookId/index.tsx"
    },
    "/map/$bookId/section/$id": {
      "filePath": "map.$bookId/section.$id.tsx",
      "children": [
        "/map/$bookId/section/$id/$focusedId/modal"
      ]
    },
    "/wizforms/$bookId/$focusedId/modal": {
      "filePath": "wizforms/$bookId.$focusedId.modal.tsx",
      "parent": "/wizforms/$bookId"
    },
    "/map/$bookId/section/$id/$focusedId/modal": {
      "filePath": "map.$bookId/section.$id.$focusedId.modal.tsx",
      "parent": "/map/$bookId/section/$id"
    }
  }
}
ROUTE_MANIFEST_END */
