syntax = "proto3";
package book_enums;
option optimize_for = SPEED;

enum WizformElementType {
    WIZFORM_ELEMENT_TYPE_NEUTRAL_ONE = 0;
    WIZFORM_ELEMENT_TYPE_NATURE = 1;
    WIZFORM_ELEMENT_TYPE_AIR = 2;
    WIZFORM_ELEMENT_TYPE_WATER = 3;
    WIZFORM_ELEMENT_TYPE_LIGHT = 4;
    WIZFORM_ELEMENT_TYPE_ENERGY = 5;
    WIZFORM_ELEMENT_TYPE_PSI = 6;
    WIZFORM_ELEMENT_TYPE_STONE = 7;
    WIZFORM_ELEMENT_TYPE_ICE = 8;
    WIZFORM_ELEMENT_TYPE_FIRE = 9;
    WIZFORM_ELEMENT_TYPE_DARK = 10;
    WIZFORM_ELEMENT_TYPE_CHAOS = 11;
    WIZFORM_ELEMENT_TYPE_METALL = 12;
    WIZFORM_ELEMENT_TYPE_NEUTRAL_TWO = 13;
    WIZFORM_ELEMENT_TYPE_CUSTOM_1 = 14;
    WIZFORM_ELEMENT_TYPE_CUSTOM_2 = 15;
    WIZFORM_ELEMENT_TYPE_CUSTOM_3 = 16;
    WIZFORM_ELEMENT_TYPE_CUSTOM_4 = 17;
    WIZFORM_ELEMENT_TYPE_CUSTOM_5 = 18;

    WIZFORM_ELEMENT_TYPE_ALL = 100;
}

enum MagicElementType {
    MAGIC_ELEMENT_TYPE_NONE = 0;
    MAGIC_ELEMENT_TYPE_NATURE = 1;
    MAGIC_ELEMENT_TYPE_AIR = 2;
    MAGIC_ELEMENT_TYPE_WATER = 3;
    MAGIC_ELEMENT_TYPE_LIGHT = 4;
    MAGIC_ELEMENT_TYPE_ENERGY = 5;
    MAGIC_ELEMENT_TYPE_PSI = 6;
    MAGIC_ELEMENT_TYPE_STONE = 7;
    MAGIC_ELEMENT_TYPE_ICE = 8;
    MAGIC_ELEMENT_TYPE_FIRE = 9;
    MAGIC_ELEMENT_TYPE_DARK = 10;
    MAGIC_ELEMENT_TYPE_CHAOS = 11;
    MAGIC_ELEMENT_TYPE_METALL = 12;
    MAGIC_ELEMENT_TYPE_JOKER = 13;
    MAGIC_ELEMENT_TYPE_ERROR = 100;
}

enum ItemTransformType {
    ITEM_TRANSFORM_TYPE_FROM = 0;
    ITEM_TRANSFORM_TYPE_TO = 1;
}